name: Locust summary

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install bugout-locust
      - name: Generate Locust summary
        run: |
          COMMENTS_URL=$(python -c 'import json; import os; event = os.environ.get("GITHUB_EVENT_PATH"); raw = open(event); inp_json = json.load(raw); print(inp_json.get("pull_request").get("_links").get("comments").get("href")); raw.close();')
          INITIAL_REF=$(python -c 'import json; import os; event = os.environ.get("GITHUB_EVENT_PATH"); raw = open(event); inp_json = json.load(raw); print(inp_json.get("pull_request").get("base").get("sha")); raw.close();')
          TERMINAL_REF=$(python -c 'import json; import os; event = os.environ.get("GITHUB_EVENT_PATH"); raw = open(event); inp_json = json.load(raw); print(inp_json.get("pull_request").get("head").get("sha")); raw.close();')
          locust --format json $INITIAL_REF $TERMINAL_REF --metadata "{\"comments_url\": \"${COMMENTS_URL}\", \"terminal_hash\": \"$TERMINAL_REF\"}" | tee summary
      - name: Cleaning summary
        id: clean_summary
        run: |
          summary=$(cat summary)
          summary="${summary//'%'/'%25'}"
          summary="${summary//$'\n'/'%0A'}"
          summary="${summary//$'\r'/'%0D'}"
          echo "::set-output name=summary::$summary"
      - name: Test
        run: |
          locust.github initial
          locust.github terminal
          locust.github repo
#       - name: Upload locust results to Bugout
#         env:
#           BUGOUT_SECRET: ${{ secrets.BUGOUT_SECRET }}
#           BUGOUT_API_URL: ${{ secrets.BUGOUT_API_URL }}
#         run: |
#           curl -k -X POST "$BUGOUT_API_URL/github/summary" \
#             -H "Content-Type: application/json" \
#             -H "Authorization: Bearer $BUGOUT_SECRET" \
#             --data '${{ steps.clean_summary.outputs.summary }}'
